In [16]:
# Enrico Borriello
# enrico.borriello@asu.edu

# Dec 11, 2020
# Review phase of https://arxiv.org/abs/2010.12075

# As part of our answer to the reviewers, we are checking our scaling law for random threshold networks.
# These are the seven networks with zero threshold that significantly exceed log2r

In [17]:
import numpy as np
import networkx as nx
import pandas as pd
import matplotlib.pyplot as plt

import ThresholdBooleanNetworks as nt

In [18]:
# Bryan's inputs
net16 = '201211_large_control_kernel_networks/201211_random_16_tpNone_seed1968.pkl'
net20 = '201211_large_control_kernel_networks/201211_random_20_tpNone_seed2460.pkl'
net30 = '201211_large_control_kernel_networks/201211_random_30_tpNone_seed3690.pkl'
net35 = '201211_large_control_kernel_networks/201211_random_35_tpNone_seed4305.pkl'
net40 = '201211_large_control_kernel_networks/201211_random_40_tpNone_seed4920.pkl'
net45 = '201211_large_control_kernel_networks/201211_random_45_tpNone_seed5535.pkl'
net46 = '201211_large_control_kernel_networks/201211_random_46_tpNone_seed5658.pkl'
net49 = '201211_large_control_kernel_networks/201211_random_49_tp0.5_seed6027.pkl'
net70 = '201211_large_control_kernel_networks/201211_random_70_tpNone_seed8610.pkl'

In [19]:
data = pd.read_pickle(net16)
data

{u'attractors': [[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
  [[1, 1, 0, 1, 1, 1, 0, 0, 1, 0]],
  [[1, 1, 0, 1, 1, 1, 0, 0, 1, 1]],
  [[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]]],
 u'control kernels': [{0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
  {0, 9},
  {9},
  {0, 1, 3, 4, 5, 7, 8, 9}],
 u'thresholds': array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]),
 u'weights': array([[ 0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1., -1.],
        [ 0.,  0., -1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0., -1.,  0., -1., -1.,  0.],
        [ 0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.],
        [ 0.,  1.,  0.,  0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  0.,  0., -1.,  0., -1.,  0.,  0.,  0.,  0.],
        [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  1., -1.,  0.,  0.]])}

In [20]:
# For some reason, Doug's code uses the transpose of the actual adjacency matrix. 
# This is why I'm transposing the input Bryan sent me.
A = np.transpose(data['weights'])
B = data['thresholds']

In [21]:
n = len(A)

In [22]:
# Generate a networkX graph, and check the number of connected components
G = nx.from_numpy_matrix(A, create_using=None)
nx.number_connected_components(G)

1

In [23]:
# Bryan's using the 0-convention for the threshold function (ThresholdBooleanNetworks.py)

In [24]:
convention = 0
with open('transitions.dat','w+') as t:
    for label in range(0,np.power(2,n)):
        t.write(str(label)+'\t'+str(nt.transition(A,B,convention,label))+'\n')

In [25]:
# Transition matrix (label 1 to label 2)
T = np.loadtxt('transitions.dat',dtype=int)

In [26]:
att = nt.find_attractors(T)

In [27]:
att

[[[16], 1], [[882], 422], [[883], 600], [[0], 1]]

In [28]:
def CKsize(attractor_label):
    for i in range(len(data['attractors'])):
        if nt.state_to_label(data['attractors'][i][0]) == attractor_label:
            return len(data['control kernels'][i])

In [29]:
for a in att:
    for i in range(len(a[0])):
        print(nt.label_to_state (a[0][i], n))
    print('basin size = ' , a[1])
    print('|CK| = ' , CKsize(a[0][0]))
    print('')

[0 0 0 0 0 1 0 0 0 0]
('basin size = ', 1)
('|CK| = ', 8)

[1 1 0 1 1 1 0 0 1 0]
('basin size = ', 422)
('|CK| = ', 2)

[1 1 0 1 1 1 0 0 1 1]
('basin size = ', 600)
('|CK| = ', 1)

[0 0 0 0 0 0 0 0 0 0]
('basin size = ', 1)
('|CK| = ', 10)



In [30]:
# !rm transitions.dat