In [2]:
import numpy as np
import networkx as nx
import pandas as pd
import matplotlib.pyplot as plt

import ThresholdBooleanNetworks as nt

In [25]:
A = np.array([
    [2,2,-1],
    [-1,0,3],
    [2,0,0]
])

B = np.array([1,1,0])

In [4]:
n = len(A)

In [5]:
# Generate a networkX graph, and check the number of connected components
G = nx.from_numpy_matrix(A, create_using=None)
nx.number_connected_components(G)

1

In [27]:
convention = 1
with open('transitions.dat','w+') as t:
    for label in range(0,np.power(2,n)):
        t.write(str(label)+'\t'+str(nt.transition(A,B,convention,label))+'\n')

In [28]:
# Transition matrix (label 1 to label 2)
T = np.loadtxt('transitions.dat',dtype=int)

In [29]:
att = nt.find_attractors(T)

In [30]:
att

[[[0], 1], [[7], 1], [[1, 4, 6, 3], 6]]

In [32]:
for a in att:
    for i in range(len(a[0])):
        print(nt.label_to_state (a[0][i], n))
    print('basin size = ' , a[1])
    print('')

[0 0 0]
basin size =  1

[1 1 1]
basin size =  1

[0 0 1]
[1 0 0]
[1 1 0]
[0 1 1]
basin size =  6

