In [1]:
import numpy as np
import networkx as nx
import pandas as pd
import matplotlib.pyplot as plt

import ThresholdBooleanNetworks as nt

In [137]:
A = np.array([
    [2,2,-1],
    [-1,0,3],
    [2,0,0]
])

B = [1,1,0]

In [138]:
# Generate a networkX graph, and check the number of connected components
G = nx.from_numpy_matrix(np.array(A), create_using=None)
nx.number_connected_components(G)

1

In [139]:
def find_attractors(matrix,thresholds,convention=1):
    A = np.array(matrix)
    B = np.array(thresholds)
    n = len(A)
    with open('transitions.dat','w+') as t:
        for label in range(0,np.power(2,n)):
            t.write(str(label)+'\t'+str(nt.transition(A,B,convention,label))+'\n')
    T = np.loadtxt('transitions.dat',dtype=int)
    att = nt.find_attractors(T)
    return att

In [149]:
def visualize_attractors (attractors, size):
    att = attractors
    for a in att:
        for i in range(len(a[0])):
            print(nt.label_to_state (a[0][i], size))
        print('basin size (num. states) = ' , a[1])
        print('basin size (%) = ' , 100*a[1]/(2**size))
        print('')

In [150]:
visualize_attractors(find_attractors(A,B),len(A))

[0 0 0]
basin size (num. states) =  1
basin size (%) =  12.5

[1 1 1]
basin size (num. states) =  1
basin size (%) =  12.5

[0 0 1]
[1 0 0]
[1 1 0]
[0 1 1]
basin size (num. states) =  6
basin size (%) =  75.0



In [151]:
A2 = np.block([[A,A],[A,A]])
B2 = B*2

visualize_attractors(find_attractors(A2,B2),len(A2))

[0 0 0 0 0 0]
basin size (num. states) =  1
basin size (%) =  1.5625

[1 1 1 1 1 1]
basin size (num. states) =  63
basin size (%) =  98.4375



In [143]:
A4 = np.block([[A2,A2],[A2,A2]])
B4 = B*4

visualize_attractors(find_attractors(A4,B4),len(A4))

[0 0 0 0 0 0 0 0 0 0 0 0]
basin size =  0.0244140625

[1 1 1 1 1 1 1 1 1 1 1 1]
basin size =  99.9755859375



In [148]:
for x1 in range(2):
    for x2 in range(2):
        for x3 in range(2):
            print(x1,x2,x3,'  ',4*x1-2*x2+4*x3-1)

0 0 0    -1
0 0 1    3
0 1 0    -3
0 1 1    1
1 0 0    3
1 0 1    7
1 1 0    1
1 1 1    5
